### ISSUE TITLE
Resign MySQL DB Schema in the Design Document

### ISSUE THREAD

**Issue by cjackie** [Wolfie-Home/Documents#2] opened 2016-08-18 15:51 UTC
The schema needs to be changed and removes JSON objects in the table. And express relationships in a database way.
similar issue: [1](https://github.com/Wolfie-Home/webserver2/issues/3)
Reasons:
- cleaner design; easy to reason and think about.
- conform to convention. As a result, potential reuse of existing library, code or algorithm.
- performance(not that important, since it is a small project)

**Comment by cjackie** [comment] 2016-08-18 15:52
Make change to [db_redesign](https://github.com/Wolfie-Home/Documents/tree/db_redesign) branch

**Comment by kbumsik** [comment] 2016-08-18 20:21
I got it.
I just wondering if you use any specific UML/ER Diagram tool use used [here](https://github.com/Wolfie-Home/Documents/blob/master/Design%20Document/Design%20Document.md#2-overview), or any tool you recommend? I personally using [StarUML](http://staruml.io/) and it is pretty good one not yet 100% satisfied....

**Comment by cjackie** [comment] 2016-08-18 20:50
@kbumsik 
Check out [mysql-workbench](https://www.mysql.com/products/workbench/). It has [ER diagram creation capability](https://dev.mysql.com/doc/workbench/en/wb-creating-eer-diagram.html), and others(creating tables, adding row/columns and many more).

Nice things about mysql-workbench:
- generate code from ER diagram
- export/import data and schema
- UI for creating simple mysql statements

A drawback:
It is MySQL only. Compared to StarUML, it is less generic.

To install and use it:

``` shell
sudo apt-get install mysql-workbench
# launch it
mysql-workbench
```

**Comment by kbumsik** [comment] 2016-08-18 21:50
@cjackie Cool! I didn't though of using ER diagram creation in mysql Workbench. It draws diagrams pretty. Thank you about this.

**Comment by kbumsik** [comment] 2016-08-19 06:54
First draft of DB design uploaded. Details like table columns, foreign keys, and typo are subject to change. But the overall idea is quite confirmed. `.mdj` file is a StarUML file.
Notice that our `modules` becomes `devices` and `room` becomes `location`, to make it more generic.
I will write corresponding changes(data structure of modules) to `Design_Document.md` tonight.
About the DB design document, I will write a new `.md` file.

Take a look if you have time. Feel free to ask!

**Comment by cjackie** [comment] 2016-08-19 14:56
Great work! Although the schema is complicated and queries will be complicated as well, it is far more generic and logical than my design. But you know, a lot of DB schema used in business is something like this. I think it is good.

One small suggestion:
user should has the ability to own devices without actually putting them in a location. In other word, there should be 1-N relationship between User table and Device table.

I can start code the db schema using Django ORM with you design when you are done.

**Comment by kbumsik** [comment] 2016-08-19 18:31
Thanks commenting on this.
About your suggestion, you are completely right. I didn't think of the fact that a device can have no location. As you can see I made `Owner??` column in `Device` table, being unsure if I really need this. Now I have to remove the question mark of `Owener??` and make `LocationRef` NULLABLE.

It may look a little bit complicated to write them in Django ORM. But I can write this DB schema by writing `CREATE TABLE` SQLs very qiuckly. 

We can probably [use this](https://docs.djangoproject.com/en/1.10/howto/legacy-databases/) to get Django `Model` codes from already created table. In other words, we can create table using my `CREATE TABLE` SQLs first and then try to use migration tool I mentioned.

**Comment by cjackie** [comment] 2016-08-19 22:34
> We can probably use this to get Django Model codes from already created table. In other words, we can create table using my CREATE TABLE SQLs first and then try to use migration tool I mentioned.

Yep. let's go for this approach. Please give me a copy of DB schema when you are done, I want to do the migration.

**Comment by kbumsik** [comment] 2016-08-21 14:10
Sorry for being late. It took more time to write my internship final report. 
I updated my design and `CREATE TABLE` SQL. You can directly execute the whole file (beware of the already existed tables, no conflict though)
Also, there is `.mwb` file. It is `mysql-workbench` ER Diagram files.
By using `python manage.py inspectdb` at the root directory of `webserver2` it generates well, but I found out few potential mismatches:
1. I can't find a correspondence to `DEFAULT NOW()` constraint to `CreatedDate` columns in Auto-generated codes. Maybe we should put [auto_now=True, auto_now_add=True](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.DateField) manually? By the way. In our Django application server, `CreatedDate` columns are not really needed, except `Datarecord` and `RecordFieldValue` tables. I put `CreatedDate` columns to the all table just for database management purpose. We can exclude them in the Django code.
2. In the DB, I set UNSIGNED constraints to the idx columns. But I cannot a correspondence in the auto-generated as well.

I hop it will be useful. Apart from relaying on Django ORM. I will also write SP (stored procedures) as well.

**Comment by cjackie** [comment] 2016-08-22 15:08
@kbumsik 
Haha, do you have to do a presentation at the end as well? I had to do one for my internship. Anyway, good job.

So, I have tried to import your DB schema with the following command:

```
mysql -u [username] -p[password] [db] < Create_tables.sql 
```

and I recieved:
_ERROR 1067 (42000) at line 11: Invalid default value for 'CreatedTime'_

**Comment by kbumsik** [comment] 2016-08-22 15:44
@cjackie Actually both...I need to do a presentation at the company and I also need to send a report to a professor (I am doing internship as credit...ESE488)

I run exactly same thing as you

>  mysql -u wolfie -p"dummypass" wolfie_home < Create_tables.sql

It works with no error. Your error seems to be it does not recognize `NOW()` function as `datetime` datatype....It shouldn't be like that.

EDIT:
Oh I found the solution.
I am currently using `mysql Ver 14.14 Distrib 5.7.13`. It looks like older versions of `mysql` does not allow us to use `NOW()` function as a default value.
Just for a quick fix, could you change any code

>  DEFAULT NOW()

with this?

> DEFAULT CURRENT_TIMESTAMP

By the way, I will make a major change in the database tables tonight. Please use the current code just for testing with django

**Comment by kbumsik** [comment] 2016-08-22 15:48
Oh I found the solution.
I am currently using `mysql Ver 14.14 Distrib 5.7.13`. It looks like older version of mysql does not allow us to use NOW() function as a default value.
Just for a quick fix, could you change any code
>  DEFAULT NOW()

with this?
> DEFAULT CURRENT_TIMESTAMP

By the way, I will make a major change in the database tables tonight. Use the current code just for testing with django

**Comment by kbumsik** [comment] 2016-08-23 15:10
The schema of the tables are pretty much confirmed.
Here are the brief list what I did.
- Introduced surrogate keys for the all tables. My initial though I could use string as key but integer surrogate key will have a better performance.
- Some [normalization](https://en.wikipedia.org/wiki/Database_normalization#List_of_Normal_Forms) applied across the tables. And reduced the maximum string length of value table. See [the reason here](https://github.com/Wolfie-Home/Documents/blob/ed6fd8bb6fc8a6883741eaab7bd8e7ac1cc62895/Design%20Document/DataBase_Design.jpg).
- Included `ModifiedDate` columns. `CreatedDate` and `ModifiedDate` will be updated automatically.
- Made `user` table to store SHA-512 encrypted password and salt.
- More detailed view of the `.jpg` diagram.

I think I will add a new table to store reserved device names. But that won't be considered in the django code. So you don't need to worry about it.

**Comment by kbumsik** [comment] 2016-08-24 00:23
Hello,
I made basic SPs for user, location, device, dataType, and datafield!

You can try following.
1. Create tables using `Create_tables.sql` (this will purge existing tables and create new ones)
2. Execute ALL of the `.sql` file in `Design Document/SQL/Programmability/`. Order is not important. Just execute all of them.
3. Then execute `Create_default_data.sql` You are going to want to see the source code of this.

Now we can use these SPs to deal with database. It's good to integrate with Django.
All of files I added are well-commented with examples. So you should be able to catch what these SPs do.

Now I will make examples of JSON and try to find out how to store JSON file into the tables

**Comment by cjackie** [comment] 2016-08-24 05:42
@kbumsik 
I actually tried Create_tables.sql today and got some errors again related to  timestamp. I'm using mysql veriosn 5.5

I will try it again tomorrow.

**Comment by cjackie** [comment] 2016-08-25 15:44
@kbumsik 
Great job! You have done a lot. I will merge it to the master branch. 

I will start thinking about how to integrate what you have to Django. I will move to the Programmability directory to webserver2 repo. since this is design document. It should only specify architecture and data format. Leave the programming stuff to webserver2 repo.

I think we are done with this. Should I close this issue?

**Comment by kbumsik** [comment] 2016-08-25 19:56
Sure. I will close it.

**Closed as completed by kbumsik** 2016-08-25 19:56 UTC
